API version Update
adafruit/Glider-for-iOS pull request #27
Opened 2024-04-03 20:17 UTC by TrevKnows

This PR updates the Transfer File web API version. The update involves modifications to the JSON structure with the latest version of CircuitPython. Changes include:

- Nesting file listings under a `files` object
- Adding folder information to the JSON response
- Incrementing the API version to 4

2024-04-03 20:54 UTC, tannewt requested changes
Thanks! Just a couple questions.

2024-04-03 20:54 UTC, tannewt commented on Glider.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Why make this lower?

2024-04-03 20:54 UTC, tannewt commented on Glider/Views/FileExplorerView.swift
> +            )
What does this do?

2024-04-03 21:52 UTC, TrevKnows commented on Glider.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Since this update is a patch, I've updated the project version to (2.1.0) Build (1). Previously 2.1.0 build (4)

2024-04-03 21:53 UTC, TrevKnows commented on Glider/Views/FileExplorerView.swift
> +            )
This creates a mock UI view in Xcode. This way, developers know what the view will look like before compiling on a device. It's also used for UI tests.

This part wasn't shown:
"struct FileExplorerView_Previews: PreviewProvider {"

2024-04-04 13:55 UTC, TrevKnows reviewed
@tannewt  Let me know if you have any more questions.

2024-04-04 16:57 UTC, tannewt commented on Glider/Views/FileExplorerView.swift
> +            )
Ah, ok. :+1:

2024-04-04 16:57 UTC, tannewt commented on Glider.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
OK!

2024-04-04 16:58 UTC, tannewt approved these changes
Thank you for the explanations!

2024-04-04 17:04 UTC, merged